// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="motion_planner,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.978000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=42,HLS_SYN_LUT=65,HLS_VERSION=2018_2}" *)

module motion_planner (
        ap_clk,
        ap_rst_n,
        homed_V,
        er_V,
        en_V,
        enable_V,
        s_axi_mp_AWVALID,
        s_axi_mp_AWREADY,
        s_axi_mp_AWADDR,
        s_axi_mp_WVALID,
        s_axi_mp_WREADY,
        s_axi_mp_WDATA,
        s_axi_mp_WSTRB,
        s_axi_mp_ARVALID,
        s_axi_mp_ARREADY,
        s_axi_mp_ARADDR,
        s_axi_mp_RVALID,
        s_axi_mp_RREADY,
        s_axi_mp_RDATA,
        s_axi_mp_RRESP,
        s_axi_mp_BVALID,
        s_axi_mp_BREADY,
        s_axi_mp_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;
parameter    C_S_AXI_MP_DATA_WIDTH = 32;
parameter    C_S_AXI_MP_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_MP_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [0:0] homed_V;
input  [0:0] er_V;
input  [0:0] en_V;
output  [0:0] enable_V;
input   s_axi_mp_AWVALID;
output   s_axi_mp_AWREADY;
input  [C_S_AXI_MP_ADDR_WIDTH - 1:0] s_axi_mp_AWADDR;
input   s_axi_mp_WVALID;
output   s_axi_mp_WREADY;
input  [C_S_AXI_MP_DATA_WIDTH - 1:0] s_axi_mp_WDATA;
input  [C_S_AXI_MP_WSTRB_WIDTH - 1:0] s_axi_mp_WSTRB;
input   s_axi_mp_ARVALID;
output   s_axi_mp_ARREADY;
input  [C_S_AXI_MP_ADDR_WIDTH - 1:0] s_axi_mp_ARADDR;
output   s_axi_mp_RVALID;
input   s_axi_mp_RREADY;
output  [C_S_AXI_MP_DATA_WIDTH - 1:0] s_axi_mp_RDATA;
output  [1:0] s_axi_mp_RRESP;
output   s_axi_mp_BVALID;
input   s_axi_mp_BREADY;
output  [1:0] s_axi_mp_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [0:0] er_V_0_data_reg;
reg    er_V_0_vld_reg;
reg    er_V_0_ack_out;
reg   [0:0] en_V_0_data_reg;
reg    en_V_0_vld_reg;
reg    en_V_0_ack_out;
reg   [0:0] enable_V_1_data_reg;
reg    enable_V_1_vld_reg;
reg    enable_V_1_vld_in;
reg    enable_V_1_ack_in;
wire   [0:0] p_en_V_fu_59_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] not_er_V_fu_53_p2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 er_V_0_data_reg = 1'd0;
#0 er_V_0_vld_reg = 1'b0;
#0 en_V_0_data_reg = 1'd0;
#0 en_V_0_vld_reg = 1'b0;
#0 enable_V_1_data_reg = 1'd0;
#0 enable_V_1_vld_reg = 1'b0;
end

motion_planner_mp_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_MP_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_MP_DATA_WIDTH ))
motion_planner_mp_s_axi_U(
    .AWVALID(s_axi_mp_AWVALID),
    .AWREADY(s_axi_mp_AWREADY),
    .AWADDR(s_axi_mp_AWADDR),
    .WVALID(s_axi_mp_WVALID),
    .WREADY(s_axi_mp_WREADY),
    .WDATA(s_axi_mp_WDATA),
    .WSTRB(s_axi_mp_WSTRB),
    .ARVALID(s_axi_mp_ARVALID),
    .ARREADY(s_axi_mp_ARREADY),
    .ARADDR(s_axi_mp_ARADDR),
    .RVALID(s_axi_mp_RVALID),
    .RREADY(s_axi_mp_RREADY),
    .RDATA(s_axi_mp_RDATA),
    .RRESP(s_axi_mp_RRESP),
    .BVALID(s_axi_mp_BVALID),
    .BREADY(s_axi_mp_BREADY),
    .BRESP(s_axi_mp_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (en_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (en_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (en_V_0_vld_reg == 1'b1)))) begin
        en_V_0_data_reg <= en_V;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (enable_V_1_vld_reg == 1'b0) & (enable_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (enable_V_1_vld_in == 1'b1) & (enable_V_1_vld_reg == 1'b1)))) begin
        enable_V_1_data_reg <= p_en_V_fu_59_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (er_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (er_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (er_V_0_vld_reg == 1'b1)))) begin
        er_V_0_data_reg <= er_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (enable_V_1_ack_in == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (enable_V_1_ack_in == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (enable_V_1_ack_in == 1'b1))) begin
        en_V_0_ack_out = 1'b1;
    end else begin
        en_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((enable_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (enable_V_1_vld_reg == 1'b1)))) begin
        enable_V_1_ack_in = 1'b1;
    end else begin
        enable_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        enable_V_1_vld_in = 1'b1;
    end else begin
        enable_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (enable_V_1_ack_in == 1'b1))) begin
        er_V_0_ack_out = 1'b1;
    end else begin
        er_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (enable_V_1_ack_in == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign enable_V = enable_V_1_data_reg;

assign not_er_V_fu_53_p2 = (er_V_0_data_reg ^ 1'd1);

assign p_en_V_fu_59_p2 = (not_er_V_fu_53_p2 & en_V_0_data_reg);

endmodule //motion_planner
