// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSCURVE_H
#define XSCURVE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xscurve_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Scrv_BaseAddress;
} XScurve_Config;
#endif

typedef struct {
    u32 Scrv_BaseAddress;
    u32 IsReady;
} XScurve;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XScurve_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XScurve_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XScurve_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XScurve_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XScurve_Initialize(XScurve *InstancePtr, u16 DeviceId);
XScurve_Config* XScurve_LookupConfig(u16 DeviceId);
int XScurve_CfgInitialize(XScurve *InstancePtr, XScurve_Config *ConfigPtr);
#else
int XScurve_Initialize(XScurve *InstancePtr, const char* InstanceName);
int XScurve_Release(XScurve *InstancePtr);
#endif

void XScurve_Start(XScurve *InstancePtr);
u32 XScurve_IsDone(XScurve *InstancePtr);
u32 XScurve_IsIdle(XScurve *InstancePtr);
u32 XScurve_IsReady(XScurve *InstancePtr);
void XScurve_EnableAutoRestart(XScurve *InstancePtr);
void XScurve_DisableAutoRestart(XScurve *InstancePtr);

void XScurve_Set_L(XScurve *InstancePtr, u32 Data);
u32 XScurve_Get_L(XScurve *InstancePtr);
void XScurve_Set_J(XScurve *InstancePtr, u32 Data);
u32 XScurve_Get_J(XScurve *InstancePtr);
void XScurve_Set_vs(XScurve *InstancePtr, u32 Data);
u32 XScurve_Get_vs(XScurve *InstancePtr);
void XScurve_Set_ve(XScurve *InstancePtr, u32 Data);
u32 XScurve_Get_ve(XScurve *InstancePtr);
void XScurve_Set_v(XScurve *InstancePtr, u32 Data);
u32 XScurve_Get_v(XScurve *InstancePtr);
u64 XScurve_Get_freq(XScurve *InstancePtr);
u32 XScurve_Get_freq_vld(XScurve *InstancePtr);

void XScurve_InterruptGlobalEnable(XScurve *InstancePtr);
void XScurve_InterruptGlobalDisable(XScurve *InstancePtr);
void XScurve_InterruptEnable(XScurve *InstancePtr, u32 Mask);
void XScurve_InterruptDisable(XScurve *InstancePtr, u32 Mask);
void XScurve_InterruptClear(XScurve *InstancePtr, u32 Mask);
u32 XScurve_InterruptGetEnabled(XScurve *InstancePtr);
u32 XScurve_InterruptGetStatus(XScurve *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
