// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// scrv
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of L
//        bit 31~0 - L[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of J
//        bit 31~0 - J[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of vs
//        bit 31~0 - vs[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of ve
//        bit 31~0 - ve[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of v
//        bit 31~0 - v[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of freq
//        bit 31~0 - freq[31:0] (Read)
// 0x3c : Data signal of freq
//        bit 31~0 - freq[63:32] (Read)
// 0x40 : Control signal of freq
//        bit 0  - freq_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSCURVE_SCRV_ADDR_AP_CTRL   0x00
#define XSCURVE_SCRV_ADDR_GIE       0x04
#define XSCURVE_SCRV_ADDR_IER       0x08
#define XSCURVE_SCRV_ADDR_ISR       0x0c
#define XSCURVE_SCRV_ADDR_L_DATA    0x10
#define XSCURVE_SCRV_BITS_L_DATA    32
#define XSCURVE_SCRV_ADDR_J_DATA    0x18
#define XSCURVE_SCRV_BITS_J_DATA    32
#define XSCURVE_SCRV_ADDR_VS_DATA   0x20
#define XSCURVE_SCRV_BITS_VS_DATA   32
#define XSCURVE_SCRV_ADDR_VE_DATA   0x28
#define XSCURVE_SCRV_BITS_VE_DATA   32
#define XSCURVE_SCRV_ADDR_V_DATA    0x30
#define XSCURVE_SCRV_BITS_V_DATA    32
#define XSCURVE_SCRV_ADDR_FREQ_DATA 0x38
#define XSCURVE_SCRV_BITS_FREQ_DATA 64
#define XSCURVE_SCRV_ADDR_FREQ_CTRL 0x40

