// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xscurve.h"

extern XScurve_Config XScurve_ConfigTable[];

XScurve_Config *XScurve_LookupConfig(u16 DeviceId) {
	XScurve_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSCURVE_NUM_INSTANCES; Index++) {
		if (XScurve_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XScurve_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XScurve_Initialize(XScurve *InstancePtr, u16 DeviceId) {
	XScurve_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XScurve_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XScurve_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

