// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmanage.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XManage_CfgInitialize(XManage *InstancePtr, XManage_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Man_BaseAddress = ConfigPtr->Man_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XManage_Start(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL) & 0x80;
    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL, Data | 0x01);
}

u32 XManage_IsDone(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XManage_IsIdle(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XManage_IsReady(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XManage_EnableAutoRestart(XManage *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL, 0x80);
}

void XManage_DisableAutoRestart(XManage *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_AP_CTRL, 0);
}

void XManage_Set_homing(XManage *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_HOMING_DATA, Data);
}

u32 XManage_Get_homing(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_HOMING_DATA);
    return Data;
}

u32 XManage_Get_f(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_F_DATA);
    return Data;
}

u32 XManage_Get_f_vld(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_F_CTRL);
    return Data & 0x1;
}

void XManage_Set_k(XManage *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_K_DATA, Data);
}

u32 XManage_Get_k(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_K_DATA);
    return Data;
}

void XManage_Set_monitor(XManage *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_MONITOR_DATA, Data);
}

u32 XManage_Get_monitor(XManage *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_MONITOR_DATA);
    return Data;
}

void XManage_InterruptGlobalEnable(XManage *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_GIE, 1);
}

void XManage_InterruptGlobalDisable(XManage *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_GIE, 0);
}

void XManage_InterruptEnable(XManage *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_IER);
    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_IER, Register | Mask);
}

void XManage_InterruptDisable(XManage *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_IER);
    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_IER, Register & (~Mask));
}

void XManage_InterruptClear(XManage *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XManage_WriteReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_ISR, Mask);
}

u32 XManage_InterruptGetEnabled(XManage *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_IER);
}

u32 XManage_InterruptGetStatus(XManage *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XManage_ReadReg(InstancePtr->Man_BaseAddress, XMANAGE_MAN_ADDR_ISR);
}

