// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMANAGE_H
#define XMANAGE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmanage_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Man_BaseAddress;
} XManage_Config;
#endif

typedef struct {
    u32 Man_BaseAddress;
    u32 IsReady;
} XManage;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XManage_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XManage_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XManage_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XManage_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XManage_Initialize(XManage *InstancePtr, u16 DeviceId);
XManage_Config* XManage_LookupConfig(u16 DeviceId);
int XManage_CfgInitialize(XManage *InstancePtr, XManage_Config *ConfigPtr);
#else
int XManage_Initialize(XManage *InstancePtr, const char* InstanceName);
int XManage_Release(XManage *InstancePtr);
#endif

void XManage_Start(XManage *InstancePtr);
u32 XManage_IsDone(XManage *InstancePtr);
u32 XManage_IsIdle(XManage *InstancePtr);
u32 XManage_IsReady(XManage *InstancePtr);
void XManage_EnableAutoRestart(XManage *InstancePtr);
void XManage_DisableAutoRestart(XManage *InstancePtr);

void XManage_Set_homing(XManage *InstancePtr, u32 Data);
u32 XManage_Get_homing(XManage *InstancePtr);
u32 XManage_Get_f(XManage *InstancePtr);
u32 XManage_Get_f_vld(XManage *InstancePtr);
void XManage_Set_k(XManage *InstancePtr, u32 Data);
u32 XManage_Get_k(XManage *InstancePtr);
void XManage_Set_monitor(XManage *InstancePtr, u32 Data);
u32 XManage_Get_monitor(XManage *InstancePtr);

void XManage_InterruptGlobalEnable(XManage *InstancePtr);
void XManage_InterruptGlobalDisable(XManage *InstancePtr);
void XManage_InterruptEnable(XManage *InstancePtr, u32 Mask);
void XManage_InterruptDisable(XManage *InstancePtr, u32 Mask);
void XManage_InterruptClear(XManage *InstancePtr, u32 Mask);
u32 XManage_InterruptGetEnabled(XManage *InstancePtr);
u32 XManage_InterruptGetStatus(XManage *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
