// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmanage.h"

extern XManage_Config XManage_ConfigTable[];

XManage_Config *XManage_LookupConfig(u16 DeviceId) {
	XManage_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMANAGE_NUM_INSTANCES; Index++) {
		if (XManage_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XManage_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XManage_Initialize(XManage *InstancePtr, u16 DeviceId) {
	XManage_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XManage_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XManage_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

