// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// man
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of homing
//        bit 31~0 - homing[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of f
//        bit 31~0 - f[31:0] (Read)
// 0x1c : Control signal of f
//        bit 0  - f_ap_vld (Read/COR)
//        others - reserved
// 0x20 : Data signal of k
//        bit 31~0 - k[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of monitor
//        bit 0  - monitor[0] (Read/Write)
//        others - reserved
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMANAGE_MAN_ADDR_AP_CTRL      0x00
#define XMANAGE_MAN_ADDR_GIE          0x04
#define XMANAGE_MAN_ADDR_IER          0x08
#define XMANAGE_MAN_ADDR_ISR          0x0c
#define XMANAGE_MAN_ADDR_HOMING_DATA  0x10
#define XMANAGE_MAN_BITS_HOMING_DATA  32
#define XMANAGE_MAN_ADDR_F_DATA       0x18
#define XMANAGE_MAN_BITS_F_DATA       32
#define XMANAGE_MAN_ADDR_F_CTRL       0x1c
#define XMANAGE_MAN_ADDR_K_DATA       0x20
#define XMANAGE_MAN_BITS_K_DATA       32
#define XMANAGE_MAN_ADDR_MONITOR_DATA 0x28
#define XMANAGE_MAN_BITS_MONITOR_DATA 1

