// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xscurve.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XScurve_CfgInitialize(XScurve *InstancePtr, XScurve_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Scrv_BaseAddress = ConfigPtr->Scrv_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XScurve_Start(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL) & 0x80;
    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL, Data | 0x01);
}

u32 XScurve_IsDone(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XScurve_IsIdle(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XScurve_IsReady(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XScurve_EnableAutoRestart(XScurve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL, 0x80);
}

void XScurve_DisableAutoRestart(XScurve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_AP_CTRL, 0);
}

void XScurve_Set_L(XScurve *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_L_DATA, Data);
}

u32 XScurve_Get_L(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_L_DATA);
    return Data;
}

void XScurve_Set_J(XScurve *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_J_DATA, Data);
}

u32 XScurve_Get_J(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_J_DATA);
    return Data;
}

void XScurve_Set_vs(XScurve *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_VS_DATA, Data);
}

u32 XScurve_Get_vs(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_VS_DATA);
    return Data;
}

void XScurve_Set_ve(XScurve *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_VE_DATA, Data);
}

u32 XScurve_Get_ve(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_VE_DATA);
    return Data;
}

void XScurve_Set_v(XScurve *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_V_DATA, Data);
}

u32 XScurve_Get_v(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_V_DATA);
    return Data;
}

u64 XScurve_Get_freq(XScurve *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_FREQ_DATA);
    Data += (u64)XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_FREQ_DATA + 4) << 32;
    return Data;
}

u32 XScurve_Get_freq_vld(XScurve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_FREQ_CTRL);
    return Data & 0x1;
}

void XScurve_InterruptGlobalEnable(XScurve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_GIE, 1);
}

void XScurve_InterruptGlobalDisable(XScurve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_GIE, 0);
}

void XScurve_InterruptEnable(XScurve *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_IER);
    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_IER, Register | Mask);
}

void XScurve_InterruptDisable(XScurve *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_IER);
    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_IER, Register & (~Mask));
}

void XScurve_InterruptClear(XScurve *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_WriteReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_ISR, Mask);
}

u32 XScurve_InterruptGetEnabled(XScurve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_IER);
}

u32 XScurve_InterruptGetStatus(XScurve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScurve_ReadReg(InstancePtr->Scrv_BaseAddress, XSCURVE_SCRV_ADDR_ISR);
}

