# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/MahanBastani/AppData/Roaming/Xilinx/Vivado/DMA_test/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MahanBastani/AppData/Roaming/Xilinx/Vivado/DMA_test/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/hailstone_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/MahanBastani/AppData/Roaming/Xilinx/Vivado/DMA_test/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/MahanBastani/AppData/Roaming/Xilinx/Vivado/DMA_test/solution1/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/hailstone_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
