# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_motion_planner_0_0/design_1_motion_planner_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_motion_planner_0_0 || ORIG_REF_NAME==design_1_motion_planner_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_supervisor_0_2/design_1_supervisor_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_supervisor_0_2 || ORIG_REF_NAME==design_1_supervisor_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_e_supervisor_0_1/design_1_e_supervisor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_e_supervisor_0_1 || ORIG_REF_NAME==design_1_e_supervisor_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_gen_0_2/design_1_pulse_gen_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_pulse_gen_0_2 || ORIG_REF_NAME==design_1_pulse_gen_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_step_counter_0_2/design_1_step_counter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_step_counter_0_2 || ORIG_REF_NAME==design_1_step_counter_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_0_0/design_1_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PWM_0_0 || ORIG_REF_NAME==design_1_PWM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_home_mgr_0_0/design_1_home_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_home_mgr_0_0 || ORIG_REF_NAME==design_1_home_mgr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_config_block_0_0/design_1_config_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_config_block_0_0 || ORIG_REF_NAME==design_1_config_block_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_scurve_0_0/design_1_scurve_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_scurve_0_0 || ORIG_REF_NAME==design_1_scurve_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_read_out_0_0/design_1_read_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_read_out_0_0 || ORIG_REF_NAME==design_1_read_out_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_0/design_1_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_0 || ORIG_REF_NAME==design_1_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_0/design_1_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_0 || ORIG_REF_NAME==design_1_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
